 #
# Macro file for "AmBe.cc"
#
/control/verbose 2
/run/verbose 1

#/control/verbose 0
#/tracking/verbose 0
#/event/verbose 0
#/gps/verbose 2


#
##/testhadr/det/setAbsorMat BeO
##/testhadr/det/setContMat Stainless-Steel
##/testhadr/det/setAbsorRadius 15 mm
##/testhadr/det/setAbsorLength 60 mm
##/testhadr/det/setContThick  2.4 mm
#
/run/initialize
#
/process/list
#
#/gun/particle ion
#/gun/ion 95 241
#/gun/energy 0. eV
#

/gun/particle deuteron
#/gun/energy 39.2 MeV
/gun/energy 28 MeV

#gaussian energy distribution
/gps/pos/type Point
#/gps/pos/cente 0 0 0 cm
/gps/particle deuteron
/gps/ene/type Gauss
/gps/ene/mono 35. MeV
/gps/ene/sigma 0. MeV
/gps/direction 0 0 1


#exponential energy distribution
#/gps/particle deuteron
#/gps/ene/type Exp
#/gps/ene/min 2. MeV
#/gps/ene/max 10. MeV
#/gps/ene/ezero 2.

#
/analysis/setFileName normal
/analysis/h1/set 4 100  0. 10.  MeV #gammas
/analysis/h1/set 6  100  0. 40.  MeV #neutrons
/analysis/h1/set 7  100 0. 40.  MeV #protons
/analysis/h1/set 8  100  0. 40.  MeV #deuterons
/analysis/h1/set 9  60  0. 30.  MeV #alphas
/analysis/h1/set 14  50  0. 4.  radian #angular neutrons
/analysis/h1/set 15  100  0. 4.  radian #angular protons
/analysis/h1/set 16  100  0. 4.  radian #angular deutrons
/run/printProgress 200000
/run/beamOn 20000000	#1e8 events

/analysis/setFileName 1mmGraphite28MeVDeut2
/analysis/h1/set 4 100  0. 10.  MeV #gammas
/analysis/h1/set 6  100  0. 40.  MeV #neutrons
/analysis/h1/set 7  100 0. 40.  MeV #protons
/analysis/h1/set 8  100  0. 40.  MeV #deuterons
/analysis/h1/set 9  60  0. 30.  MeV #alphas
/analysis/h1/set 14  100  0. 4.  radian #angular
/run/printProgress 2000000
/run/beamOn 200000000	#1e8 events

/analysis/setFileName 1mmGraphite28MeVDeut3
/analysis/h1/set 4 100  0. 10.  MeV #gammas
/analysis/h1/set 6  100  0. 40.  MeV #neutrons
/analysis/h1/set 7  100 0. 40.  MeV #protons
/analysis/h1/set 8  100  0. 40.  MeV #deuterons
/analysis/h1/set 9  60  0. 30.  MeV #alphas
/analysis/h1/set 14  100  0. 4.  radian #angular
/run/printProgress 2000000
/run/beamOn 200000000	#1e8 events

/analysis/setFileName 1mmGraphite28MeVDeut4
/analysis/h1/set 4 100  0. 10.  MeV #gammas
/analysis/h1/set 6  100  0. 40.  MeV #neutrons
/analysis/h1/set 7  100 0. 40.  MeV #protons
/analysis/h1/set 8  100  0. 40.  MeV #deuterons
/analysis/h1/set 9  60  0. 30.  MeV #alphas
/analysis/h1/set 14  100  0. 4.  radian #angular
/run/printProgress 2000000
/run/beamOn 200000000	#1e8 events

/analysis/setFileName 1mmGraphite28MeVDeut5
/analysis/h1/set 4 100  0. 10.  MeV #gammas
/analysis/h1/set 6  100  0. 40.  MeV #neutrons
/analysis/h1/set 7  100 0. 40.  MeV #protons
/analysis/h1/set 8  100  0. 40.  MeV #deuterons
/analysis/h1/set 9  60  0. 30.  MeV #alphas
/analysis/h1/set 14  100  0. 4.  radian #angular
/run/printProgress 2000000
/run/beamOn 200000000	#1e8 events

/analysis/setFileName 1mmGraphite28MeVDeut6
/analysis/h1/set 4 100  0. 10.  MeV #gammas
/analysis/h1/set 6  100  0. 40.  MeV #neutrons
/analysis/h1/set 7  100 0. 40.  MeV #protons
/analysis/h1/set 8  100  0. 40.  MeV #deuterons
/analysis/h1/set 9  60  0. 30.  MeV #alphas
/analysis/h1/set 14  100  0. 4.  radian #angular
/run/printProgress 2000000
/run/beamOn 200000000	#1e8 events

/analysis/setFileName 1mmGraphite28MeVDeut7
/analysis/h1/set 4 100  0. 10.  MeV #gammas
/analysis/h1/set 6  100  0. 40.  MeV #neutrons
/analysis/h1/set 7  100 0. 40.  MeV #protons
/analysis/h1/set 8  100  0. 40.  MeV #deuterons
/analysis/h1/set 9  60  0. 30.  MeV #alphas
/analysis/h1/set 14  100  0. 4.  radian #angular
/run/printProgress 2000000
/run/beamOn 200000000	#1e8 events

/analysis/setFileName 1mmGraphite28MeVDeut8
/analysis/h1/set 4 100  0. 10.  MeV #gammas
/analysis/h1/set 6  100  0. 40.  MeV #neutrons
/analysis/h1/set 7  100 0. 40.  MeV #protons
/analysis/h1/set 8  100  0. 40.  MeV #deuterons
/analysis/h1/set 9  60  0. 30.  MeV #alphas
/analysis/h1/set 14  100  0. 4.  radian #angular
/run/printProgress 2000000
/run/beamOn 200000000	#1e8 events

/analysis/setFileName 1mmGraphite28MeVDeut9
/analysis/h1/set 4 100  0. 10.  MeV #gammas
/analysis/h1/set 6  100  0. 40.  MeV #neutrons
/analysis/h1/set 7  100 0. 40.  MeV #protons
/analysis/h1/set 8  100  0. 40.  MeV #deuterons
/analysis/h1/set 9  60  0. 30.  MeV #alphas
/analysis/h1/set 14  100  0. 4.  radian #angular
/run/printProgress 1000000
/run/beamOn 200000000	#1e8 events

/analysis/setFileName 1mmGraphite28MeVDeut10
/analysis/h1/set 4 100  0. 10.  MeV #gammas
/analysis/h1/set 6  100  0. 40.  MeV #neutrons
/analysis/h1/set 7  100 0. 40.  MeV #protons
/analysis/h1/set 8  100  0. 40.  MeV #deuterons
/analysis/h1/set 9  60  0. 30.  MeV #alphas
/analysis/h1/set 14  100  0. 4.  radian #angular
/run/printProgress 2000000
/run/beamOn 200000000	#1e8 events

/analysis/setFileName 1mmGraphite28MeVDeut11
/analysis/h1/set 4 100  0. 10.  MeV #gammas
/analysis/h1/set 6  100  0. 40.  MeV #neutrons
/analysis/h1/set 7  100 0. 40.  MeV #protons
/analysis/h1/set 8  100  0. 40.  MeV #deuterons
/analysis/h1/set 9  60  0. 30.  MeV #alphas
/analysis/h1/set 14  100  0. 4.  radian #angular
/run/printProgress 2000000
/run/beamOn 200000000	#1e8 events



#
#/run/printProgress 1000
#/run/beamOn 100000	#1e5 events
#/run/printProgress 100000
#/run/beamOn 10000000	#1e7 events
#/run/printProgress 1000000
#/run/beamOn 100000000	#1e8 events
#/run/printProgress 10000000
#/run/beamOn 1000000000 #1e9 events
#
#/run/beamOn 2000000000	#Max number events for 32 bit integer
